export const siteConfig = {
  title: '爪印小站',
  titleEn: 'Pawprint Notes',
  mark: '爪',
  romanizedName: 'Xu Fengjun',
  author: '徐丰俊',
  tagline: '把好奇心装进口袋，在开源世界里慢慢散步，喵～',
  taglineEn: 'Collecting whimsical ideas and wandering through the open-source world.',
  description: '爪印小站（Pawprint Notes）是徐丰俊的个人网站，主要用于自我介绍，并提供公开联系方式。',
  url: 'https://ansujuner.github.io',
  locale: 'zh-CN',
  timezone: 'Asia/Shanghai',
  since: 2026,
  profile: {
    initial: '徐',
    role: '在校学生',
    roleEn: 'Student',
    location: '杭州',
    locationEn: 'Hangzhou',
    interest: '喜欢有想象力的小项目',
    interestEn: 'Imaginative projects',
    belief: '坚定的开源主义者',
    beliefEn: 'Open source',
  },
  now: '文章区暂时空着，等有想写的内容，再慢慢添上。',
  nowEn: 'The notes section is quiet for now; I’ll add to it when there is something to share.',
  nav: [
    { label: '首页', labelEn: 'Home', href: '/' },
    { label: '关于', labelEn: 'About', href: '/about/' },
    { label: '联系', labelEn: 'Contact', href: '/#contact' },
  ],
  social: {
    github: 'https://github.com/ansujuner',
    email: '1795811354@qq.com',
    bilibili: 'https://space.bilibili.com/3493136561081252',
    bilibiliName: 'bili_94968455178',
  },
} as const;

export type SiteConfig = typeof siteConfig;
