export const siteConfig = {
  title: '爪印小站',
  titleEn: 'Pawprint Notes',
  mark: '爪',
  romanizedName: 'Xu Fengjun',
  author: '徐丰俊',
  tagline: '在杭州上学，喜欢开源和天马星空的项目，喵。',
  taglineEn: 'A student in Hangzhou who likes open source and imaginative projects — meow.',
  description: '爪印小站（Pawprint Notes）是徐丰俊的个人网站，放着简单的自我介绍与公开联系方式。',
  url: 'https://ansujuner.github.io',
  locale: 'zh-CN',
  timezone: 'Asia/Shanghai',
  since: 2026,
  profile: {
    initial: '徐',
    role: '在校学生',
    roleEn: 'Student',
    location: '杭州',
    locationEn: 'Hangzhou',
    interest: '喜欢天马星空的项目',
    interestEn: 'Imaginative projects',
    belief: '坚定的开源主义者',
    beliefEn: 'Open source',
  },
  now: '在杭州上学，关注天马星空的项目和开源。',
  nowEn: 'Studying in Hangzhou, with an interest in imaginative projects and open source.',
  nav: [
    { label: '首页', labelEn: 'Home', href: '/' },
    { label: '关于', labelEn: 'About', href: '/about/' },
    { label: '联系', labelEn: 'Contact', href: '/#contact' },
  ],
  social: {
    github: 'https://github.com/ansujuner',
    email: '1795811354@qq.com',
    bilibili: 'https://space.bilibili.com/3493136561081252',
    bilibiliName: 'bili_94968455178',
  },
} as const;

export type SiteConfig = typeof siteConfig;
